# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photogram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Photogram
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Analytics'
  # Firebase Authentication SDK
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
